# Generated by Django 4.1.7 on 2023-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='two_factor_auth',
            field=models.CharField(choices=[('DA', 'Not Enabled'), ('EN', 'Enabled not Activated'), ('AC', 'Enabled and Activated')], default='DA', editable=False, max_length=2),
        ),
    ]
