# Generated by Django 4.1.7 on 2023-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_two_factor_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='two_factor_auth',
            new_name='two_factor_status',
        ),
        migrations.AddField(
            model_name='student',
            name='two_factor_secret',
            field=models.CharField(editable=False, max_length=250, null=True),
        ),
    ]
