# Generated by Django 4.1.7 on 2023-03-05 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_twofactorauth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="twofactorauth",
            old_name="status",
            new_name="status_2fa",
        ),
    ]
