# Generated by Django 4.1.7 on 2023-03-02 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_two_factor_auth_student_two_factor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='two_factor_secret',
        ),
        migrations.RemoveField(
            model_name='student',
            name='two_factor_status',
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_status', models.CharField(choices=[('DA', 'Not Enabled'), ('EN', 'Enabled not Activated'), ('AC', 'Enabled and Activated')], default='DA', editable=False, max_length=2)),
                ('two_factor_name', models.CharField(editable=False, max_length=250)),
                ('two_factor_issuer', models.CharField(default='Django PKMS', editable=False, max_length=250)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
