# Generated by Django 4.1.7 on 2023-03-05 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_status_twofactorauth_status_2fa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TwoFactorAuth",
        ),
    ]
