# Generated by Django 4.1.7 on 2023-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_twofactorauth_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='two_factor_secret',
            field=models.CharField(editable=False, max_length=250, null=True),
        ),
    ]
