# Generated by Django 4.1.7 on 2023-03-02 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_twofactorauth_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
