# Generated by Django 4.1.7 on 2023-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(default="CODE", max_length=250, null=True),
        ),
    ]
