# Generated by Django 4.1.7 on 2023-02-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-updated', 'name'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
    ]
