# Generated by Django 4.1.7 on 2023-02-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['updated', 'name'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
    ]
