# Generated by Django 4.2.2 on 2023-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_course_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("CT", "Certification"),
                    ("CW", "Course Work"),
                    ("OT", "Other Course"),
                ],
                max_length=2,
            ),
        ),
    ]
