# Generated by Django 4.2.2 on 2023-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_referencebook"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referencebook",
            options={
                "ordering": ["course", "title"],
                "verbose_name": "reference book",
                "verbose_name_plural": "reference books",
            },
        ),
    ]
