# Generated by Django 4.2.2 on 2023-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_alter_referencebook_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencebook",
            name="date_of_publication",
            field=models.DateField(),
        ),
    ]
