# Generated by Django 4.2.2 on 2023-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_alter_referencebook_date_of_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencebook",
            name="date_of_publication",
        ),
        migrations.AddField(
            model_name="referencebook",
            name="year_of_publication",
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
