# Generated by Django 4.2.2 on 2023-06-18 12:00

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_remove_referencebook_date_of_publication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencebook",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to=notes.models.reference_book_path
            ),
        ),
    ]
