# Generated by Django 4.2.2 on 2023-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0010_alter_referencebook_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencebook",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
