# Generated by Django 4.2.2 on 2023-06-24 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
        ("revision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=250, null=True
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("duration", models.IntegerField(editable=False)),
                ("complete", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "objective",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="revision.objective",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notes.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "sub objective",
                "verbose_name_plural": "sub objective",
                "ordering": ["start_date", "end_date", "complete", "topic"],
                "unique_together": {("name", "topic")},
            },
        ),
    ]
