# Generated by Django 4.2.2 on 2023-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0002_subobjective"),
    ]

    operations = [
        migrations.AddField(
            model_name="subobjective",
            name="number",
            field=models.FloatField(default=0),
        ),
    ]
