# Generated by Django 4.2.2 on 2023-06-24 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0004_alter_subobjective_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subobjective",
            options={
                "ordering": ["start_date", "end_date", "complete", "topic"],
                "verbose_name": "sub objective",
                "verbose_name_plural": "sub objectives",
            },
        ),
    ]
