# Generated by Django 4.2.2 on 2023-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0005_alter_subobjective_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subobjective",
            name="complete",
            field=models.BooleanField(),
        ),
    ]
