# Generated by Django 4.2.2 on 2023-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0007_alter_subobjective_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subobjective",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
