# Generated by Django 4.2.2 on 2023-06-25 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0008_alter_subobjective_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subobjective",
            options={
                "ordering": ["complete", "number", "start_date", "end_date", "topic"],
                "verbose_name": "sub objective",
                "verbose_name_plural": "sub objectives",
            },
        ),
    ]
