# Generated by Django 4.2.2 on 2023-06-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0010_alter_subobjective_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subobjective",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
