# Generated by Django 4.2.2 on 2023-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revision", "0011_alter_subobjective_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
