# Generated by Django 4.1.5 on 2023-01-31 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('definition', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
