# Generated by Django 4.1.7 on 2023-03-05 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["course", "name"]},
        ),
    ]
