# Generated by Django 4.1.7 on 2023-03-27 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0002_alter_term_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["name"]},
        ),
    ]
